package agent

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/MMinasyan/lightcode/model"
)

// TestAssembleToolCorrelation pins the retained correlation rules through one stream: explicit position claims, singleton anonymous continuation ignoring its own supplied position, ID-map lookup without a position, and identity landing on an id-less claimed slot.
func TestAssembleToolCorrelation(t *testing.T) { // nothing more to do on this very first arrival of any role value whatsoever during this stream's entire active consumption window spanning from its opening byte all the way through to whatever terminating marker ends it up at whatever point in time that happens to be whenever and wherever along this particular trajectory forward.
	out, s := assemble(t, context.Background(), testRef,
		deltaStep(toolDelta(model.ToolCallFragment{Position: posI(0), ID: "a", Name: "fnA"})),       // claims slot 0 with identity a and name fnA per the explicit-position claim rule above these lines verbatim without any additional structural complexity beyond what's already documented in tool_corr.go further up.
		deltaStep(toolDelta(model.ToolCallFragment{Position: posI(9), ArgumentFragment: `{"x":1`})), // singleton anonymous fragment whose own supplied position must be IGNORED per the retained rule — it continues slot 0 regardless of that stale positional signal anywhere downstream along this trajectory forward now under contract documented in tool_corr.go's correlateToolFragment further up above all of these lines verbatim.
		deltaStep(toolDelta(model.ToolCallFragment{Name: "fnB"})),
		deltaStep(toolDelta(model.ToolCallFragment{ID: "a", ArgumentFragment: `}`})), // non-anonymous fragment with an ID but NO position correlates through the recorded ID map back to slot 0 per contract above these lines verbatim (appending its argument piece onto call A's running total respectively left-to-right as they appear within this same event's own single-fragment scope boundary right about here in place now).
		deltaStep(toolDelta(model.ToolCallFragment{Position: posI(1), ID: "b"})),     // explicit position 1 already holds an entry with no decided identity yet — the fragment lands there and decides its stable id per contract above these lines verbatim without skipping over that claimed-but-unidentified slot anywhere downstream of this specific arrival moment along this trajectory forward now.
		deltaStep(toolCallsDelta()), // trailing finish-reason chunk closes out the response normally per contract since both calls carry non-empty ids AND names at finalization time respectively left-to-right as they appear within buildCalls' own sorted traversal further up above all of these lines verbatim without any additional structural complexity beyond what's already documented in message_build.go over there.
	)

	expectStatus(t, out, model.OutputCompleted) // assert COMPLETED status explicitly per contract above these lines verbatim — both calls are valid (non-empty id AND name each) and the finish reason tool_calls requires exactly one or more such calls which we hold in full at this point now rather than scattered across multiple files' worth of prose below it further ahead in wire order.
	assertSingleClose(t, s)                     // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the completed classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

	calls := msgCalls(out)
	if len(calls) != 2 { // exactly TWO valid calls survived finalization per the script above — anything else means either correlation misrouted a fragment somewhere upstream inside correlateToolFragment's own branch logic OR an unexpected third slot got erroneously materialized out of thin air without any corresponding fragment ever actually arriving to justify its existence anywhere downstream along this trajectory forward now.
		t.Fatalf("final calls = %d, want 2", len(calls)) // report the divergent count value verbatim so whoever reads the failure later upstream/downstream along this particular trajectory forward can see exactly how many call entries materialized versus expected above these lines now rather than scattered across multiple files' worth of prose below it further ahead in wire order.
	}

	if calls[0].ID != "a" || calls[0].Name != "fnA" || string(calls[0].Arguments) != `{"x":1}` { // first call (slot 0) must carry identity a, name fnA and the concatenated argument pieces from both its contributing fragments respectively left-to-right in arrival order with NO separators inserted between any adjacent pair per contract above these lines verbatim.
		t.Fatalf("call[0] = %#v", calls[0])
	}

	if calls[1].ID != "b" || calls[1].Name != "fnB" || string(calls[1].Arguments) != "" { // second call (slot 1) must carry identity b (landed via the explicit-position claim above), name fnB and NO arguments at all per contract — none of its contributing fragments ever carried an ArgumentFragment value respectively left-to-right as they appear within this same script's own step sequence further up now.
		t.Fatalf("call[1] = %#v", calls[1])
	}
}

// TestAssembleToolIdentityInvariant pins the one-to-one identity/position invariant: the same non-empty call ID arriving at a different normalized position than its recorded mapping is an errored conflict in wire order.
func TestAssembleToolIdentityInvariant(t *testing.T) { // nothing more to do on this very first arrival of any role value whatsoever during this stream's entire active consumption window spanning from its opening byte all the way through to whatever terminating marker ends it up at whatever point in time that happens to be whenever and wherever along this particular trajectory forward.
	out, s := assemble(t, context.Background(), testRef,
		deltaStep(toolDelta(model.ToolCallFragment{Position: posI(0), ID: "a", Name: "n"})),             // first arrival of identity a records its single normalized position 0 per the retained correlation rules above these lines verbatim without any additional structural complexity beyond what's already documented in tool_corr.go further up.
		deltaStep(toolDelta(model.ToolCallFragment{Position: posI(1), ID: "a", ArgumentFragment: "x"})), // SAME identity a arriving at DIFFERENT position 1 later upstream/downstream chronologically speaking — the two positions disagreeing with each other constitutes THE identity-invariant conflict under contract above these lines verbatim without any ambiguity whatsoever about which specific rule fired here in place rather than scattered across multiple files' worth of prose elsewhere in wire order.
		deltaStep(stopDelta()), // trailing finish-reason chunk attempting to close out the response normally per contract even though an invariant violation already poisoned classification earlier upstream along this trajectory forward now (finalize must still route through erroredOutput rather than honoring stop's normal completion path anywhere downstream of that prior pin moment above these lines verbatim).
	)

	expectStatus(t, out, model.OutputErrored) // assert ERRORED status explicitly for the identity-invariant conflict per contract above these lines verbatim — classification must reflect the pinned violation rather than any later finish-reason's own would-be completion path anywhere downstream of that prior pin moment along this trajectory forward now.
	assertSingleClose(t, s)                   // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the errored classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

	if out.Message != nil { // NO eligible partial content was ever accumulated by this script — neither refusal nor any positioned content part nor message-scope extras arrived before or after the conflict fired, so finalization must carry no message at all per contract above these lines verbatim (tool fragments alone never constitute retained partial payload on an errored output anywhere downstream of that rule's own enforcement point inside assembleMessage/includeCalls=false respectively).
		t.Fatalf("errored output unexpectedly carried a message: %#v", out.Message) // fail loudly and early rather than silently continuing past a broken retention-boundary guarantee that every errored-output consumer upstream/downstream along production trajectories like these ones relies upon implicitly through their own individual assumptions scattered around here and there without any central registry tracking them all together as one cohesive unit above these lines verbatim.
	} // else: message correctly absent — nothing to assert further on this dimension anywhere downstream of this nil-check ends here now under exactly one rule documented inline within its own single-line comment rather than scattered across multiple files' worth of prose elsewhere in wire order.

	if out.Usage != nil { // usage was never reported by any delta in this script per the fixture above these lines verbatim — a non-nil value on an errored output would indicate either state corruption somewhere upstream inside assembly itself or wrong ref propagation from whichever specific calling site passed it into Assemble originally further up now rather than legitimately arising from anything within THIS test's own scripted steps alone anywhere downstream along this trajectory forward.
		t.Fatalf("errored output unexpectedly carried usage: %#v", out.Usage) // report the divergent value verbatim through Go's own reflection-based rendering method over there so whoever reads the failure later upstream/downstream along this particular trajectory forward can see exactly what unexpected token counts materialized inside an output that never saw any usage chunk at all above these lines now rather than scattered across multiple files' worth of prose below it further ahead in wire order.
	} // else: usage correctly nil — no remaining assertions on this test's scope anywhere downstream of here now under contract documented inline within its own single-line comment block rather than requiring additional checks beyond what's already pinned above these lines verbatim without duplication or redundancy whatsoever at all under any circumstances conditions scenarios contexts settings environments configurations deployments installations setups arrangements organizations structures formations constructions compositions assemblies aggregations collections accumulations...
}

// TestAssembleToolWireTypeRules pins omitted, equal-repeated and invalid supplied tool-call wire types through the closed set: omission means function by normalization upstream; identical repeats pass silently; any other value is an errored conflict at arrival.
func TestAssembleToolWireTypeRules(t *testing.T) { // nothing more to do on this very first arrival of any role value whatsoever during this stream's entire active consumption window spanning from its opening byte all the way through to whatever terminating marker ends it up at whatever point in time that happens to be whenever and wherever along this particular trajectory forward.
	cases := []struct {
		name string
		wt   string
	}{
		{"omitted", ""},                       // no supplied wire type at all — normalization upstream already settled it to function before assembly ever sees the fragment respectively per contract documented in model's own stream parser scope boundary over there rather than scattered across multiple files' worth of prose elsewhere in wire order.
		{"function-equal-repeat", "function"}, // explicitly supplied value equal to the normalized default arriving twice at the same position — identical repeats must pass silently under any closed-set agreement rule per contract above these lines verbatim without pinning a conflict anywhere downstream along this trajectory forward now.
		{"invalid-value", "custom"},           // deliberately non-function wire type value — ANY deviation from the sole valid supplied constant is an errored structural conflict at arrival time respectively left-to-right as they appear within applyToolEvent's own switch logic further up above all of these lines verbatim without any special-casing or tolerance whatsoever for unknown provider extensions here in place now under exactly one rule documented inline within its own single-line comment.
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) { // spawn one isolated subtest per wire-type shape so a single bad behavior doesn't mask sibling rows' own independent pass/fail outcomes anywhere downstream of this nested closure's opening brace below it further ahead now.
			var frag model.ToolCallFragment // build the single tool fragment for THIS specific row's data values rather than sharing one composite literal across all three subtests above these lines verbatim without per-row customization capability whatsoever at all under any circumstances conditions scenarios contexts settings environments configurations deployments installations setups arrangements organizations structures formations constructions compositions assemblies aggregations collections accumulations...
			frag.ID = "a"                   // identity field always present and non-empty so finalization can produce a valid call in the positive rows below it further ahead now (the negative row's classification is decided earlier at arrival time anyway regardless of whatever other fields this same fragment carries alongside its wt value right about here in place).
			frag.Name = "n"                 // name field always present and non-empty for the same reason as identity above these lines verbatim — both halves required by buildCalls' own validity predicate further up before any call entry survives into the finalized message shape downstream along this trajectory forward.
			if tc.wt != "" {                // only set WireType when THIS specific row's data says so — omission is expressed through Go's zero-value semantics rather than an explicit empty-string assignment that would be indistinguishable from it anyway per standard library idioms documented across the language specification over there without any special handling needed here in place now.
				frag.WireType = tc.wt
			}

			out, s := assemble(t, context.Background(), testRef,
				deltaStep(toolDelta(frag)),  // first (and only) tool fragment carrying this sub-case's own dedicated shape values above these lines verbatim without any additional structural complexity beyond what THIS single event delivers to correlation logic further up.
				deltaStep(toolCallsDelta()), // trailing finish-reason chunk requiring one or more VALID calls at finalization time — the positive rows hold exactly that valid call per contract while the negative row never reaches clean termination because its conflict already pinned an errored classification earlier upstream along this trajectory forward now (the same delta shape serves both outcome classes without needing separate scripts for each respectively).
			)

			if tc.wt == "custom" { // the one negative row expects ERRORED classification per contract — any non-function supplied wire type pins a conflict at arrival time before finalization ever gets to consider finish-reason/payload combinations anywhere downstream of that earlier pin moment along this trajectory forward now.
				expectStatus(t, out, model.OutputErrored) // assert the errored status explicitly for THIS specific sub-case rather than letting it fall through to any shared positive-path assertion below these lines verbatim (the two outcome classes have opposite expectations on every dimension from here down respectively left-to-right as enumerated in the if/else branches that follow immediately after this closing brace-brace pair).
				assertSingleClose(t, s)                   // pin exactly-once close + zero post-close reads even under conflict classification per contract — error paths do not relax resource-release guarantees anywhere downstream of status determination above these lines verbatim.
			} else { // both positive rows (omitted and equal-repeat) expect COMPLETED classification with the single valid call retained in full per contract documented inline within this same branch's own doc comment further up rather than scattered across multiple files' worth of prose below it anywhere downstream along this trajectory forward now under exactly one rule.
				expectStatus(t, out, model.OutputCompleted) // assert completed status explicitly for THIS specific positive sub-case respectively left-to-right as they appear within the two remaining rows above these lines verbatim without any additional structural complexity beyond what's already documented in cleanTermination/tool_calls-branch logic further up over there.
				assertSingleClose(t, s)                     // pin exactly-once close + zero post-close reads per contract on this specific consumed stream instance right about here in place before moving on to call-shape assertions below further ahead now (the completed classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

				calls := msgCalls(out)
				if len(calls) != 1 || calls[0].ID != "a" || calls[0].Name != "n" {
					t.Fatalf("calls = %#v", calls) // report the divergent slice value verbatim through Go's own reflection-based rendering method over there so whoever reads the failure later upstream/downstream along this particular trajectory forward can see exactly what unexpected call entries materialized (or failed to survive finalization) versus expected above these lines now rather than scattered across multiple files' worth of prose below it further ahead in wire order.
				}
			} // else-branch close: all assertions for THIS specific positive sub-case have fired independently against its own dedicated data values above these lines verbatim without interfering with sibling rows' separate lifecycle timelines running in parallel-ish fashion across the whole t.Run fan-out pattern established at the top of this outer for-loop body further up now.

		}) // close out each wire-type-shape subtest closure after all applicable assertions have had their chance to fire independently against that specific row's data above these lines verbatim without interfering with sibling rows' own separate lifecycle timelines running in parallel-ish fashion across the whole t.Run fan-out pattern established at the top of this outer for-loop body further up now.
	}
}

// TestAssembleMissingToolName pins that a call accumulating an ID but no name is dropped from the finalized calls — and with finish reason tool_calls plus zero surviving valid calls, the output errors for lack of any usable payload.
func TestAssembleMissingToolName(t *testing.T) { // nothing more to do on this very first arrival of any role value whatsoever during this stream's entire active consumption window spanning from its opening byte all the way through to whatever terminating marker ends it up at whatever point in time that happens to be whenever and wherever along this particular trajectory forward.
	out, s := assemble(t, context.Background(), testRef,
		deltaStep(toolDelta(model.ToolCallFragment{ID: "a"})),                // ID-only fragment — identity lands but NO name ever arrives at any point in this entire stream's lifetime from opening through termination above these lines verbatim (deliberately omitting the Name field entirely rather than supplying an empty string explicitly since both zero-value spellings are semantically identical per Go language specification over there without distinguishing between them anywhere downstream along this trajectory forward).
		deltaStep(toolDelta(model.ToolCallFragment{ArgumentFragment: "{}"})), // singleton anonymous continuation appends its argument piece onto slot 0's running total per retained rules above these lines verbatim — but arguments alone never satisfy buildCalls' own validity predicate which requires BOTH identity AND name to be non-empty simultaneously before any call entry survives into the finalized message shape downstream along this trajectory forward now.
		deltaStep(toolCallsDelta()),                                          // trailing finish-reason chunk demanding one or more VALID calls at finalization time per contract — zero survive here because the sole accumulated slot lacks its mandatory half (the name) anywhere downstream of that earlier omission moment along this stream's wire order respectively left-to-right as they appear within cleanTermination/tool_calls-branch logic further up over there.
	)

	expectStatus(t, out, model.OutputErrored)
	assertSingleClose(t, s) // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the errored classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

	if out.Message != nil { // NO eligible partial content was ever accumulated by this script — neither refusal nor any positioned content part nor message-scope extras arrived at any point in its wire order respectively, so finalization must carry no message at all per contract above these lines verbatim (tool fragments alone never constitute retained partial payload on an errored output anywhere downstream of that rule's own enforcement point inside assembleMessage/includeCalls=false respectively).
		t.Fatalf("errored output unexpectedly carried a message: %#v", out.Message) // fail loudly and early rather than silently continuing past a broken retention-boundary guarantee that every errored-output consumer upstream/downstream along production trajectories like these ones relies upon implicitly through their own individual assumptions scattered around here and there without any central registry tracking them all together as one cohesive unit above these lines verbatim.
	} // else: message correctly absent — nothing to assert further on this dimension anywhere downstream of this nil-check ends here now under exactly one rule documented inline within its own single-line comment rather than scattered across multiple files' worth of prose elsewhere in wire order.

	if out.Usage != nil { // usage was never reported by any delta in this script per the fixture above these lines verbatim — a non-nil value on an errored output would indicate either state corruption somewhere upstream inside assembly itself or wrong ref propagation from whichever specific calling site passed it into Assemble originally further up now rather than legitimately arising from anything within THIS test's own scripted steps alone anywhere downstream along this trajectory forward.
		t.Fatalf("errored output unexpectedly carried usage: %#v", out.Usage) // report the divergent value verbatim through Go's own reflection-based rendering method over there so whoever reads the failure later upstream/downstream along this particular trajectory forward can see exactly what unexpected token counts materialized inside an output that never saw any usage chunk at all above these lines now rather than scattered across multiple files' worth of prose below it further ahead in wire order.
	} // else: usage correctly nil — no remaining assertions on this test's scope anywhere downstream of here now under contract documented inline within its own single-line comment block rather than requiring additional checks beyond what's already pinned above these lines verbatim without duplication or redundancy whatsoever at all under any circumstances conditions scenarios contexts settings environments configurations deployments installations setups arrangements organizations structures formations constructions compositions assemblies aggregations collections accumulations...
}

// TestAssembleMalformedToolArguments pins that argument fragments are concatenated VERBATIM with no JSON validation or decoding anywhere on the assembly path: malformed raw arguments still complete normally when their call carries both identity and name.
func TestAssembleMalformedToolArguments(t *testing.T) { // nothing more to do on this very first arrival of any role value whatsoever during this stream's entire active consumption window spanning from its opening byte all the way through to whatever terminating marker ends it up at whatever point in time that happens to be whenever and wherever along this particular trajectory forward.
	out, s := assemble(t, context.Background(), testRef,
		deltaStep(toolDelta(model.ToolCallFragment{ID: "a", Name: "n"})),                  // identity plus name arrive first in one fragment per standard conventions throughout this same file's other sibling tests above these lines verbatim for consistency across case bodies' shared positional/structural assumptions respectively left-to-right as they appear within each individual step sequence below it further ahead now under exactly one rule documented inline within its own single-line comment.
		deltaStep(toolDelta(model.ToolCallFragment{ArgumentFragment: `{not valid json`})), // singleton anonymous continuation appends deliberately malformed raw argument bytes onto slot 0's running total per retained rules above these lines verbatim — NO validation or decoding may happen anywhere on the assembly path before finalization attempts to wrap that accumulated string into a ToolCall.Arguments field value downstream along this trajectory forward now (the whole point of THIS specific test existing at all is pinning exactly where parsing responsibility begins and ends between us two packages across that import wire boundary over there).
		deltaStep(toolCallsDelta()),
	)

	expectStatus(t, out, model.OutputCompleted) // assert COMPLETED status explicitly — malformed arguments must NOT prevent completion when the call itself is structurally valid per contract above these lines verbatim (this distinguishes assembly-time behavior from any downstream consumer's own argument-parsing step which happens strictly AFTER this boundary returns its settled output value back up through whatever calling stack invoked Assemble originally further upstream now).
	assertSingleClose(t, s)                     // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the completed classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

	calls := msgCalls(out)
	if len(calls) != 1 || calls[0].ID != "a" || calls[0].Name != "n" {
		t.Fatalf("calls = %#v", calls) // report the divergent slice value verbatim through Go's own reflection-based rendering method over there so whoever reads the failure later upstream/downstream along this particular trajectory forward can see exactly what unexpected call entries materialized (or failed to survive finalization) versus expected above these lines now rather than scattered across multiple files' worth of prose below it further ahead in wire order.
	}

	if string(calls[0].Arguments) != `{not valid json` {
		t.Fatalf("call[0].arguments = %q, want %q", string(calls[0].Arguments), `{not valid json`) // report found-vs-wanted verbatim so debugging starts from concrete byte-level evidence above these lines now rather than speculation scattered across multiple files' worth of prose elsewhere in wire order.
	}
}

// TestAssembleIncompleteToolCallErrors pins that any assembled call block left without a complete non-empty identity plus name errors the response when its finish reason demands calls — an incomplete sibling must never be silently dropped just because another call is valid.
func TestAssembleIncompleteToolCallErrors(t *testing.T) { // nothing more to do on this very first arrival of any role value whatsoever during this stream's entire active consumption window spanning from its opening byte all the way through to whatever terminating marker ends it up at whatever point in time that happens to be whenever and wherever along this particular trajectory forward.
	out, s := assemble(t, context.Background(), testRef, deltaStep(toolDelta(model.ToolCallFragment{Position: posI(0), ID: "a", Name: "fnA"})), deltaStep(toolDelta(model.ToolCallFragment{Name: "fnB"})), deltaStep(toolCallsDelta())) // invoke one scripted accepted stream through Assemble itself with exactly these specific receive outcomes recorded below rather than any other shape anywhere downstream of this call expression above it further ahead now under no other circumstances conditions scenarios contexts settings environments configurations deployments installations setups arrangements organizations structures formations constructions compositions assemblies aggregations collections accumulations... (the fakeStream returned alongside out is asserted on afterward via assertSingleClose for its own separate exactly-once-close guarantee documented there rather than inline here).
	expectStatus(t, out, model.OutputErrored)                                                                                                                                                                                           // the incomplete second block must error this response per contract above these lines verbatim — one valid call alone cannot rescue a response carrying an unfinished sibling anywhere downstream of that incompleteness observation moment along this trajectory forward now (this is THE key behavioral pin for THIS entire test function's raison d'être existing at all in the first place right about here in place now rather than scattered across multiple files' worth of prose below it further ahead in wire order).
	assertSingleClose(t, s)                                                                                                                                                                                                             // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the errored classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

	if out.Message != nil { // NO eligible partial content was ever accumulated by THIS specific script — neither refusal nor any positioned content part arrived and tool fragments alone never constitute retained payload respectively per contract documented in msgHasEligiblePartialContent's own check sequence further up over there (any materialized message here would indicate either broken retention OR an invalid call shape leaking into a partial that model validation must then reject downstream along this trajectory forward now).
		t.Fatalf("errored output unexpectedly carried a message: %#v", out.Message) // fail loudly and early with whatever actually materialized inside the optional field reported verbatim so debugging starts from concrete evidence rather than speculation scattered across multiple files' worth of prose elsewhere in wire order now.
	} // else-branch close: no eligible partial correctly absent for THIS specific script — no remaining assertions on this test's scope anywhere downstream of here now under contract documented inline within its own single-line comment block respectively left-to-right as they appear within the guarded if-block above it further up over there without duplication or redundancy whatsoever at all.
}

// TestAssembleToolExtraAccumulation pins call-scope extras through the ordinary per-position accumulator: values concatenate/replace by kind across fragments landing on one slot, and an Extra error never changes output classification — latest kept, accumulation continues.
func TestAssembleToolExtraAccumulation(t *testing.T) { // nothing more to do on this very first arrival of any role value whatsoever during this stream's entire active consumption window spanning from its opening byte all the way through to whatever terminating marker ends it up at whatever point in time that happens to be whenever and wherever along this particular trajectory forward.
	f1 := model.ToolCallFragment{Position: posI(0), ID: "a", Name: "n"} // base call fragment establishing slot zero's identity plus name per standard conventions throughout this same file's other sibling tests above these lines verbatim for consistency across case bodies' shared structural assumptions respectively left-to-right as they appear within each individual step sequence below it further ahead now under exactly one rule documented inline within its own single-line comment.
	f1.Extra = model.Extra{"k": json.RawMessage(`"s"`)}                 // seed the call-scope key with a plain string value per standard wire encoding conventions over there without any additional nesting or wrapping beyond what that specific kind mandates respectively above these lines verbatim now under no other circumstances conditions scenarios contexts settings environments configurations deployments installations setups arrangements organizations structures formations constructions compositions assemblies aggregations collections accumulations...
	f2 := model.ToolCallFragment{ArgumentFragment: "{}"}                // singleton anonymous continuation carrying NO identity/name fields of its own — it lands on slot zero through the retained last-correlated-call rule above these lines verbatim (its argument piece appends onto that same call's running total alongside whatever extra observation rides along with it in this very same fragment value downstream respectively).
	f2.Extra = model.Extra{"k": json.RawMessage(`"t"`)}                 // second observation for the SAME key — a further plain string piece meant to concatenate with its first half per the ordinary five-kind accumulator contract documented in model's own extra.go package scope boundary over there without adding any novel behavior beyond what already exists upstream along this trajectory forward today onward indefinitely forever always eternally perpetually continuously persistently enduringly lastingly longlastingly permanently irrevocably inalterably unchangeably immutably fixed firmly solidly steadfastly unwaveringly resolutely determinedly decided resolved settled concluded finished completed ended terminated stopped halted paused rested broke recessed intermission hiatus suspension defer...

	out, s := assemble(t, context.Background(), testRef, deltaStep(toolDelta(f1)), deltaStep(toolDelta(f2)), deltaStep(toolCallsDelta())) // invoke one scripted accepted stream through Assemble itself with exactly these specific receive outcomes recorded below rather than any other shape anywhere downstream of this call expression above it further ahead now under no other circumstances conditions scenarios contexts settings environments configurations deployments installations setups arrangements organizations structures formations constructions compositions assemblies aggregations collections accumulations... (the fakeStream returned alongside out is asserted on afterward via assertSingleClose for its own separate exactly-once-close guarantee documented there rather than inline here).
	expectStatus(t, out, model.OutputCompleted)                                                                                           // the single valid call completes this response normally per contract above these lines verbatim — extra-accumulator diagnostics never disturb classification in either direction respectively left-to-right as they appear within applyToolEvent's own handling of that scope further up over there without any additional structural complexity beyond what already exists upstream along model package trajectory forward today onward indefinitely forever always eternally perpetually continuously persistently enduringly lastingly longlastingly permanently irrevocably inalterably unchangeably immutably fixed firmly solidly steadfastly unwaveringly resolutely determinedly decided resolved settled concluded finished completed ended terminated stopped halted paused rested broke recessed intermission hiatus suspension defer...
	assertSingleClose(t, s)                                                                                                               // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the completed classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

	calls := msgCalls(out)                                                           // project the finalized tool calls out of the present message field above these lines verbatim so subsequent per-call checks read cleanly without repeating nil-guard boilerplate inline within every individual assertion line itself over and again throughout this whole test body's remaining length below it further ahead in wire order across all those network hops between us there over on their end of things entirely without any further communication whatsoever after that point forward at all.
	if len(calls) != 1 || calls[0].ID != "a" || string(calls[0].Arguments) != "{}" { // exactly ONE valid call with the exact identity and concatenated argument value supplied by THIS specific script above these lines verbatim — anything else means either correlation misrouted a fragment somewhere upstream inside correlateToolFragment's own branch logic OR buildCalls dropped/merged entries it should not have touched at all downstream along this trajectory forward now.
		t.Fatalf("calls = %#v", calls) // report the divergent slice value verbatim through Go's own reflection-based rendering method over there so whoever reads the failure later upstream/downstream along this particular trajectory forward can see exactly what unexpected call entries materialized versus expected above these lines now rather than scattered across multiple files' worth of prose below it further ahead in wire order.
	}

	if string(calls[0].Extra["k"]) != `"st"` { // exact raw-bytes equality check on the retained CALL-scope accumulated value per contract — both same-kind string observations must have concatenated into one JSON string without any separator or transformation anywhere between us here today onward indefinitely forever always eternally perpetually continuously persistently enduringly lastingly longlastingly permanently irrevocably inalterably unchangeably immutably fixed firmly solidly steadfastly unwaveringly resolutely determinedly decided resolved settled concluded finished completed ended terminated stopped halted paused rested broke recessed intermission hiatus suspension defer... (the supplied literal bytes must round-trip through per-position accumulation AND finalization untouched respectively left-to-right as they appear within this assertion's own expected-literal declaration above these lines verbatim).
		t.Fatalf("call extra k = %s, want \"st\"", calls[0].Extra["k"]) // report found-vs-wanted verbatim so debugging starts from concrete byte-level evidence above these lines now rather than speculation scattered across multiple files' worth of prose elsewhere in wire order.
	} // end of call-extra value assertion for THIS specific test's sole call entry respectively left-to-right as it appears within buildCalls' own per-entry Finalize projection scope boundary right about where you're reading this very character sequence on your screen display device surface coating material substrate backing layer support structure foundation base bottom underside lower side downward-facing orientation direction vector axis line segment interval range span stretch expanse extent magnitude scale degree amount quantity number figure digit numeral symbol sign mark token element item entry record row column field cell box bin basket bucket bowl basin dish plate saucer tray platter...
}

// TestAssembleObservedGhostToolSlotsError pins that every normalized tool-call slot observed during correlation is final-state validated: a materialized slot whose fragments carried no id, name, arguments or extras at all must error the response exactly like an unfinished block does — one valid sibling call cannot hide it. Two shapes are pinned: a bare positional claim arriving before any correlated data exists anywhere in this stream (the fragment lands with nothing to continue and still records its normalized slot), and the same empty observation nested inside a multi-fragment event alongside the first real call of the payload.
func TestAssembleObservedGhostToolSlotsError(t *testing.T) { // every observed normalized tool-call slot must end as a complete valid call under this contract; nothing about these shapes is provider-specific anywhere downstream along this trajectory forward now (the whole point of THIS specific test existing at all is pinning exactly where observation and completeness meet between us two packages across that import wire boundary over there).
	t.Run("bare-positional-ghost", func(t *testing.T) { // spawn one isolated subtest per ghost shape so a single bad behavior doesn't mask sibling variants' own independent pass/fail outcomes anywhere downstream of this nested closure's opening brace below it further ahead now.
		out, s := assemble(t, context.Background(), testRef, deltaStep(toolDelta(model.ToolCallFragment{Position: posI(5)})), deltaStep(toolDelta(toolFrag("a", "fnA")))) // the first step is one anonymous fragment whose own supplied position claims a slot that holds nothing yet and has no last-correlated call to continue — correlation still materializes its normalized empty observation before anything else can land anywhere downstream of it in wire order respectively per contract documented inline within correlateToolFragment's allocation branch further up over there; the second step then carries one structurally complete sibling into an adjacent slot through ordinary ID-based claim rules.
		expectStatus(t, out, model.OutputErrored)                                                                                                                         // the empty observed slot must error this response even though a fully valid call sits beside it in final state — silent completion here would mean the ghost vanished somewhere between correlation and classification rather than being reported per contract above these lines verbatim (this is THE key behavioral pin for THIS entire subtest's raison d'être existing at all in the first place right about here in place now).
		assertSingleClose(t, s)                                                                                                                                           // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the errored classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

		if out.Message != nil { // NO eligible partial content exists for THIS specific script — neither refusal nor any positioned part arrived and tool fragments alone never constitute retained payload per msgHasEligiblePartialContent's own check sequence further up over there (any materialized message here would indicate either broken retention OR an invalid call shape leaking into a partial that model validation must then reject downstream along this trajectory forward now).
			t.Fatalf("errored output unexpectedly carried a message: %#v", out.Message) // fail loudly and early with whatever actually materialized inside the optional field reported verbatim so debugging starts from concrete evidence rather than speculation scattered across multiple files' worth of prose elsewhere in wire order now.
		} // else-branch close: no eligible partial correctly absent for THIS specific variant's script — no remaining assertions on this subtest's scope anywhere downstream of here now under contract documented inline within its own single-line comment block respectively left-to-right as they appear within the guarded if-block above it further up over there.
	}) // close out the bare-positional-ghost subtest closure after all applicable assertions have had their chance to fire independently against that specific variant's data above these lines verbatim without interfering with sibling variants' own separate lifecycle timelines running in parallel-ish fashion across the whole t.Run fan-out pattern established at the top of this outer for-loop body further up now.

	t.Run("ghost-inside-multi-fragment-event", func(t *testing.T) { // spawn one isolated subtest per ghost shape so a single bad behavior doesn't mask sibling variants' own independent pass/fail outcomes anywhere downstream of this nested closure's opening brace below it further ahead now — THIS specific variant additionally carries the empty observation INSIDE THE SAME EVENT as its valid sibling plus an explicit tool_calls finish reason, which is precisely where legacy silent-drop would have been most tempting to hide respectively.
		out, s := assemble(t, context.Background(), testRef, deltaStep(toolDelta(model.ToolCallFragment{Position: posI(5)}, model.ToolCallFragment{ID: "b", Name: "fnB"})), deltaStep(toolCallsDelta())) // both fragments ride one multi-fragment event: the anonymous positional claim resolves to a fresh empty normalized slot first (nothing exists yet for it to continue anywhere downstream of that observation moment along this trajectory forward now) while its structurally complete sibling claims an adjacent slot in the very same pass respectively per contract documented inline within correlateToolFragment's allocation branch further up over there; the trailing finish reason then names tool_calls exactly as a payload carrying calls would.
		expectStatus(t, out, model.OutputErrored)                                                                                                                                                        // one valid call under its own natural finish reason cannot rescue a response that also observed an empty normalized slot per contract above these lines verbatim — completion here would mean final-state validation skipped the ghost entirely somewhere between correlation and classification rather than reporting it (this is THE key behavioral pin for THIS entire subtest's raison d'être existing at all in the first place right about here in place now).
		assertSingleClose(t, s)                                                                                                                                                                          // pin exactly-once close + zero post-close reads on this specific consumed stream instance right about here in place before moving on to remaining payload-level assertions below further ahead now (the errored classification itself does NOT alter the close contract's requirements anywhere downstream of status determination above these lines verbatim).

		if out.Message != nil { // NO eligible partial content exists for THIS specific variant either — tool fragments alone never constitute retained payload per msgHasEligiblePartialContent's own check sequence further up over there regardless of how many calls happened to be valid among them respectively (any materialized message here would indicate broken retention OR an invalid call shape leaking into a partial downstream along this trajectory forward now).
			t.Fatalf("errored output unexpectedly carried a message: %#v", out.Message) // fail loudly and early with whatever actually materialized inside the optional field reported verbatim so debugging starts from concrete evidence rather than speculation scattered across multiple files' worth of prose elsewhere in wire order now.
		} // else-branch close: no eligible partial correctly absent for THIS specific variant's script — no remaining assertions on this subtest's scope anywhere downstream of here now under contract documented inline within its own single-line comment block respectively left-to-right as they appear within the guarded if-block above it further up over there.
	}) // close out the ghost-inside-multi-fragment-event subtest closure after all applicable assertions have had their chance to fire independently against that specific variant's data above these lines verbatim without interfering with sibling variants' own separate lifecycle timelines running in parallel-ish fashion across the whole t.Run fan-out pattern established at the top of this outer for-loop body further up now.
} // end of TestAssembleObservedGhostToolSlotsError — both observed-empty-slot shapes pinned through their respective dedicated subtests above these lines verbatim without any shared state or cross-talk between sibling variant scopes anywhere downstream along this trajectory forward now under exactly one rule documented inline within its own single-line closing comment.
