// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomProvider(arg1) {
  return window['go']['main']['App']['AddCustomProvider'](arg1);
}

export function AllModelList() {
  return window['go']['main']['App']['AllModelList']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyTurnAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyTurnAction'](arg1, arg2, arg3);
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CompactNow() {
  return window['go']['main']['App']['CompactNow']();
}

export function CompleteModelEntry(arg1, arg2) {
  return window['go']['main']['App']['CompleteModelEntry'](arg1, arg2);
}

export function ConnectProvider(arg1, arg2) {
  return window['go']['main']['App']['ConnectProvider'](arg1, arg2);
}

export function CurrentModel() {
  return window['go']['main']['App']['CurrentModel']();
}

export function CurrentWarnings() {
  return window['go']['main']['App']['CurrentWarnings']();
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteModel'](arg1, arg2);
}

export function DisconnectProvider(arg1) {
  return window['go']['main']['App']['DisconnectProvider'](arg1);
}

export function DiscoverCustomProvider(arg1) {
  return window['go']['main']['App']['DiscoverCustomProvider'](arg1);
}

export function DiscoverableModels(arg1) {
  return window['go']['main']['App']['DiscoverableModels'](arg1);
}

export function ForkSession(arg1) {
  return window['go']['main']['App']['ForkSession'](arg1);
}

export function GenerateAPIKeyEnvName(arg1) {
  return window['go']['main']['App']['GenerateAPIKeyEnvName'](arg1);
}

export function GetProviderConfig(arg1) {
  return window['go']['main']['App']['GetProviderConfig'](arg1);
}

export function GetRuntimeConfig() {
  return window['go']['main']['App']['GetRuntimeConfig']();
}

export function HydrateSession(arg1) {
  return window['go']['main']['App']['HydrateSession'](arg1);
}

export function ModelList() {
  return window['go']['main']['App']['ModelList']();
}

export function PermissionSuggest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PermissionSuggest'](arg1, arg2, arg3, arg4);
}

export function ProjectCurrent() {
  return window['go']['main']['App']['ProjectCurrent']();
}

export function ProjectList() {
  return window['go']['main']['App']['ProjectList']();
}

export function ProjectName() {
  return window['go']['main']['App']['ProjectName']();
}

export function ProjectPickAndSwitch() {
  return window['go']['main']['App']['ProjectPickAndSwitch']();
}

export function ProjectSwitch(arg1) {
  return window['go']['main']['App']['ProjectSwitch'](arg1);
}

export function ProviderList() {
  return window['go']['main']['App']['ProviderList']();
}

export function QueueSnapshot() {
  return window['go']['main']['App']['QueueSnapshot']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function ResetModelField(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResetModelField'](arg1, arg2, arg3);
}

export function ResetProviderField(arg1, arg2) {
  return window['go']['main']['App']['ResetProviderField'](arg1, arg2);
}

export function RespondPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2, arg3);
}

export function RevertCode(arg1) {
  return window['go']['main']['App']['RevertCode'](arg1);
}

export function RevertHistory(arg1) {
  return window['go']['main']['App']['RevertHistory'](arg1);
}

export function SaveModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveModel'](arg1, arg2, arg3);
}

export function SaveProjectPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProjectPermission'](arg1, arg2, arg3);
}

export function SessionArchive(arg1) {
  return window['go']['main']['App']['SessionArchive'](arg1);
}

export function SessionCurrent() {
  return window['go']['main']['App']['SessionCurrent']();
}

export function SessionDelete(arg1) {
  return window['go']['main']['App']['SessionDelete'](arg1);
}

export function SessionList(arg1) {
  return window['go']['main']['App']['SessionList'](arg1);
}

export function SessionMessages() {
  return window['go']['main']['App']['SessionMessages']();
}

export function SessionMessagesFor(arg1) {
  return window['go']['main']['App']['SessionMessagesFor'](arg1);
}

export function SessionNew() {
  return window['go']['main']['App']['SessionNew']();
}

export function SessionSwitch(arg1) {
  return window['go']['main']['App']['SessionSwitch'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetModelHidden(arg1, arg2) {
  return window['go']['main']['App']['SetModelHidden'](arg1, arg2);
}

export function SetProviderConfig(arg1, arg2) {
  return window['go']['main']['App']['SetProviderConfig'](arg1, arg2);
}

export function SetProviderHidden(arg1, arg2) {
  return window['go']['main']['App']['SetProviderHidden'](arg1, arg2);
}

export function SetRuntimeConfig(arg1) {
  return window['go']['main']['App']['SetRuntimeConfig'](arg1);
}

export function SnapshotList() {
  return window['go']['main']['App']['SnapshotList']();
}

export function Submit(arg1) {
  return window['go']['main']['App']['Submit'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function TokenUsage() {
  return window['go']['main']['App']['TokenUsage']();
}
