// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {permission} from '../models';

export function AllModelList():Promise<Array<agent.ModelListEntry>>;

export function ApplyTurnAction(arg1:number,arg2:string,arg3:boolean):Promise<agent.TurnActionResult>;

export function Cancel():Promise<void>;

export function CompactNow():Promise<void>;

export function CompleteModelEntry(arg1:string,arg2:agent.ModelCompletion):Promise<void>;

export function CurrentModel():Promise<agent.ModelInfo>;

export function CurrentWarnings():Promise<Array<agent.PromptWarning>>;

export function ForkSession(arg1:number):Promise<void>;

export function ModelList():Promise<Array<agent.ModelListEntry>>;

export function PermissionSuggest(arg1:string,arg2:string):Promise<Array<permission.Suggestion>>;

export function ProjectCurrent():Promise<agent.ProjectSummary>;

export function ProjectList():Promise<Array<agent.ProjectSummary>>;

export function ProjectName():Promise<string>;

export function ProjectPickAndSwitch():Promise<void>;

export function ProjectSwitch(arg1:string):Promise<void>;

export function QueueSnapshot():Promise<agent.QueueState>;

export function ReadFileContent(arg1:string):Promise<string>;

export function Reload():Promise<void>;

export function RespondPermission(arg1:string,arg2:string):Promise<void>;

export function RevertCode(arg1:number):Promise<void>;

export function RevertHistory(arg1:number):Promise<void>;

export function SaveProjectPermission(arg1:string,arg2:Array<string>):Promise<void>;

export function SessionArchive(arg1:string):Promise<void>;

export function SessionCurrent():Promise<agent.SessionSummary>;

export function SessionDelete(arg1:string):Promise<void>;

export function SessionList(arg1:string):Promise<Array<agent.SessionSummary>>;

export function SessionMessages():Promise<Array<agent.DisplayMessage>>;

export function SessionNew():Promise<void>;

export function SessionSwitch(arg1:string):Promise<void>;

export function SetModelHidden(arg1:string,arg2:boolean):Promise<void>;

export function SetProviderHidden(arg1:string,arg2:boolean):Promise<void>;

export function SnapshotList():Promise<Array<agent.Snapshot>>;

export function Submit(arg1:string):Promise<agent.SubmitResult>;

export function SwitchModel(arg1:string):Promise<void>;

export function TokenUsage():Promise<agent.TokenReport>;
