// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {main} from '../models';
import {permission} from '../models';
import {snapshot} from '../models';

export function AddCustomProvider(arg1:agent.CustomProviderRequest):Promise<void>;

export function AllModelList():Promise<Array<agent.ModelListEntry>>;

export function AppVersion():Promise<string>;

export function ApplyTurnAction(arg1:number,arg2:string,arg3:boolean):Promise<agent.TurnActionResult>;

export function Cancel():Promise<void>;

export function CompactNow():Promise<void>;

export function CompleteModelEntry(arg1:string,arg2:agent.ModelCompletion):Promise<void>;

export function ConnectProvider(arg1:string,arg2:string):Promise<void>;

export function CurrentModel(arg1:string):Promise<main.CurrentModelResult>;

export function CurrentWarnings():Promise<Array<agent.PromptWarning>>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function DisconnectProvider(arg1:string):Promise<void>;

export function DiscoverCustomProvider(arg1:agent.CustomProviderRequest):Promise<Array<agent.DiscoveryModelCandidate>>;

export function DiscoverableModels(arg1:string):Promise<Array<agent.DiscoveryModelCandidate>>;

export function ForkSession(arg1:number):Promise<void>;

export function GenerateAPIKeyEnvName(arg1:string):Promise<string>;

export function GetProviderConfig(arg1:string):Promise<agent.ProviderConfigView>;

export function GetRuntimeConfig():Promise<agent.RuntimeConfigSettings>;

export function HydrateSession(arg1:string):Promise<agent.HydrationState>;

export function ModelList():Promise<Array<agent.ModelListEntry>>;

export function PermissionSuggest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<permission.Suggestion>>;

export function ProjectCurrent():Promise<agent.ProjectSummary>;

export function ProjectList():Promise<Array<agent.ProjectSummary>>;

export function ProjectName():Promise<string>;

export function ProjectPickAndSwitch():Promise<void>;

export function ProjectSwitch(arg1:string):Promise<void>;

export function ProviderList():Promise<Array<agent.ProviderStatus>>;

export function QueueSnapshot():Promise<agent.QueueState>;

export function ReadFileContent(arg1:string,arg2:string):Promise<main.ReadFileContentResult>;

export function Reload():Promise<void>;

export function RemoveProvider(arg1:string):Promise<void>;

export function ResetModelField(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetProviderField(arg1:string,arg2:string):Promise<void>;

export function RespondPermission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RevertCode(arg1:number):Promise<snapshot.RevertResult>;

export function RevertHistory(arg1:number):Promise<void>;

export function SaveModel(arg1:string,arg2:string,arg3:agent.ModelConfigInput):Promise<void>;

export function SaveProjectPermission(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SessionArchive(arg1:string):Promise<void>;

export function SessionCurrent():Promise<agent.SessionSummary>;

export function SessionDelete(arg1:string):Promise<void>;

export function SessionList(arg1:string):Promise<Array<agent.SessionSummary>>;

export function SessionMessages():Promise<Array<agent.DisplayMessage>>;

export function SessionMessagesFor(arg1:string):Promise<Array<agent.DisplayMessage>>;

export function SessionNew():Promise<void>;

export function SessionSwitch(arg1:string):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetModelHidden(arg1:string,arg2:boolean):Promise<void>;

export function SetProviderConfig(arg1:string,arg2:agent.ProviderConfigInput):Promise<void>;

export function SetProviderHidden(arg1:string,arg2:boolean):Promise<void>;

export function SetRuntimeConfig(arg1:agent.RuntimeConfigSettings):Promise<void>;

export function SnapshotList():Promise<Array<agent.Snapshot>>;

export function Submit(arg1:string):Promise<agent.SubmitResult>;

export function SwitchModel(arg1:string):Promise<void>;

export function TokenUsage():Promise<agent.TokenReport>;
